/******************************************************************
 * File:        CacheManager.java
 * Created by:  Dave Reynolds
 * Created on:  13 Nov 2015
 * 
 * (c) Copyright 2015, Epimorphics Limited
 *
 *****************************************************************/

package com.epimorphics.armlib;

import java.io.File;
import java.io.InputStream;

/**
 * Cache manager implementations provide a persistent cache for the result
 * of a batch request. Implementations may support a distributed cache so that
 * results generated by one instance of the request processor can be discovered
 * and retrieved from other instances.
 * <p>The URLs used for retrieval will be a prefix, the request Key and a suffix.
 * Configured cache managers can support multiple suffixes but there should be a 
 * single default suffix.
 * </p>
 */
public interface CacheManager {

    /**
     * Set the default suffix to use for files unless explicitly overriden when uploaded
     */
    public void setDefaultSuffix(String defaultSuffix);

    /**
     * Set to true to indicate that data should be compressed in the cache.
     * When uploading an InputStream the cache manager with perform compression.
     * When uploading a file then assumes the file has already been compressed.
     */
    public void setCompressed(boolean compress);

    /**
     * Returns true if compression is enabled so that both file contents and read streams
     * will be compressed.
     */
    public boolean isCompressed();
    
    /**
     * Return the URL from which the result of the request is/will be available
     */
    public String getResultURL(BatchRequest request);
    
    /**
     * Return the URL from which the result of the request is available
     * (if the request is not complete then need the full request in order
     * to check for stickiness).
     */
    public String getResultURL(String requestKey);
    
    /**
     * Return true if the result of the given request is available.
     * This tests if the variant with the default suffix is available. 
     */
    public boolean isReady(String requestKey);
    
    /**
     * Return the result of the request as an InputStream.
     * If the cache is set to be compressed, the result will be gzip encoded.
     * Returns null if the result is not available.
     */
    public InputStream readResult(String requestKey);
    
    /**
     * Return the result of the request as an InputStream.
     * If the cache is set to be compressed, the result will be gzip encoded.
     * Returns null if the result is not available.
     */
    public InputStream readResult(String requestKey, String suffix);

    /**
     * Upload the result of a request to the persistent cache
     */
    public void upload(BatchRequest request, File result);

    /**
     * Upload the result of a request to the persistent cache
     */
    public void upload(BatchRequest request, String suffix, File result);

    /**
     * Start an upload of the result of a request to the persistent cache.
     * The caller should write the data to the output stream and then close it.
     * The cache manager will fork a thread to transfer the stream to cache.
     * If the caller does not close the outputstream a serious Thread leak will result. 
     * Uses default suffix (.csv).
     */
    public Pipe upload(BatchRequest request);

    /**
     * Start an upload of the result of a request to the persistent cache.
     * The caller should write the data to the output stream and then close it.
     * The cache manager will fork a thread to transfer the stream to cache.
     * If the caller does not close the outputstream a serious Thread leak will result.
     */
    public Pipe upload(BatchRequest request, String suffix);
    
    /**
     * Clear all cache entries - mostly useful for test harnesses
     */
    public void clear();
    
    /**
     * Clear just the non-sticky cache entries
     */
    public void clearNonSticky();
    
}
